### ISSUE TITLE
precache.py dies after downloading an item. AttributeError

### ISSUE THREAD

**Issue by GitStoph** [krypted/precache#10]
After precache.py would download an item, it would error out when moving on to the next file. I would receive the following error:

Traceback (most recent call last):
  File "/usr/local/bin/precache.py", line 1007, in <module>
    main()
  File "/usr/local/bin/precache.py", line 994, in main
    p.cache_assets(group=args.cache_group)
  File "/usr/local/bin/precache.py", line 702, in cache_assets
    if item.group in g]
  File "/usr/local/bin/precache.py", line 739, in download
    if req.info().getheader('Content-Type') is not None:
AttributeError: 'NoneType' object has no attribute 'info'

Apologies, forgot to mention i'm using precache version 1.1.2

**Comment by GitStoph** [comment]
Tried versions 1.1.1 and 1.1.0. Having issues with them as well. 2/4 of my caching servers had no issues. All have the same configs/hardware. Tried resetting the cache and copying over a "working" copy of the precache.py and continued to have the issue. 
usage was: /usr/local/bin/precache.py -cs http://127.0.0.1:(port) --cache-group Watch installer updates

**Comment by carlashley** [comment]
Thanks GitStoph (haven't had my cache box up and running to get onto this sooner) - I'll have a look and see if I can replicate the behaviour and resolve it.

**Comment by carlashley** [comment]
If you are able to replicate it, can you let me know which file it's failing on?
Run the command with the `--debug` flag, and look for the last few lines in the log when it fails.

**Comment by carlashley** [comment]
@GitStoph - I ran the same command options as you provided in your report, but I've been unable to replicate the issue (ran on an empty Cache server box).

Have you had the same issue occur again?

**Comment by GitStoph** [comment]
Sorry for not getting back to you way sooner! Slammed at work and baby at home filled my plate up pretty quick. Here's what the debug flag created:
`precache version 1.1.2
Caching Server: http://127.0.0.1:49367
Processing feeds. This may take a few moments.
Traceback (most recent call last):
  File "/usr/local/bin/precache.py", line 1007, in <module>
    main()
  File "/usr/local/bin/precache.py", line 1001, in main
    p.cache_ipsw(model=args.ipsw_model, store_in=download_dir)
  File "/usr/local/bin/precache.py", line 674, in cache_ipsw
    self.ipsw_assets_master]
  File "/usr/local/bin/precache.py", line 739, in download
    if req.info().getheader('Content-Type') is not None:
AttributeError: 'NoneType' object has no attribute 'info'
Caching WatchOS, OSX updates and installers.
precache version 1.1.2
Caching Server: http://127.0.0.1:49367
Processing feeds. This may take a few moments.
Traceback (most recent call last):
  File "/usr/local/bin/precache.py", line 1007, in <module>
    main()
  File "/usr/local/bin/precache.py", line 994, in main
    p.cache_assets(group=args.cache_group)
  File "/usr/local/bin/precache.py", line 702, in cache_assets
    if item.group in g]
  File "/usr/local/bin/precache.py", line 739, in download
    if req.info().getheader('Content-Type') is not None:
AttributeError: 'NoneType' object has no attribute 'info'
`

**Comment by GitStoph** [comment]
Ran it again outside of my script just to be sure that wasn't messing with anything. Got the same output. 

sudo /usr/local/bin/precache.py -cs http://127.0.0.1:49367 --cache-group Watch installer updates --debug
precache version 1.1.2
Caching Server: http://127.0.0.1:49367
Processing feeds. This may take a few moments.
Caching: Watch1,1 (3.1.3) [100.00% of 56.83MB]
Traceback (most recent call last):
  File "/usr/local/bin/precache.py", line 1007, in <module>
    main()
  File "/usr/local/bin/precache.py", line 994, in main
    p.cache_assets(group=args.cache_group)
  File "/usr/local/bin/precache.py", line 702, in cache_assets
    if item.group in g]
  File "/usr/local/bin/precache.py", line 739, in download
    if req.info().getheader('Content-Type') is not None:
AttributeError: 'NoneType' object has no attribute 'info'

**Comment by GitStoph** [comment]
'''
AppleCache4:~ wssadmin$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.5 (16F73)
      Kernel Version: Darwin 16.6.0
      Boot Volume: MacHD
      Boot Mode: Normal
      Computer Name: AppleCache4
      User Name: wssadmin (wssadmin)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 32 minutes
'''
This issue came back. It seemed stable for a while. I just finished updating these two servers. Is that the cause? 
'''
Traceback (most recent call last):
  File "/usr/local/bin/precache.py", line 1044, in <module>
    main()
  File "/usr/local/bin/precache.py", line 1031, in main
    p.cache_assets(group=args.cache_group)
  File "/usr/local/bin/precache.py", line 703, in cache_assets
    if item.group in g]
  File "/usr/local/bin/precache.py", line 740, in download
    if req.info().getheader('Content-Type') is not None:
AttributeError: 'NoneType' object has no attribute 'info'
Precaching has finished.
'''
